# Generated by Django 5.1.4 on 2025-01-04 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.TextField(blank=True, null=True, unique=True)),
                ("artist", models.TextField(blank=True)),
                ("title", models.TextField(blank=True)),
                ("album", models.TextField(blank=True)),
                (
                    "year",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("sweeper", models.BooleanField(default=False)),
                ("override_fade", models.BooleanField(default=False)),
                ("valid_from", models.DateTimeField(null=True)),
                ("valid_until", models.DateTimeField(null=True)),
                ("isrc", models.TextField(blank=True)),
                ("record_label", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("genre", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DayPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("permitted", models.BooleanField(default=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alldaydj.cart"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alldaydj.genre",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="tags",
            field=models.ManyToManyField(to="alldaydj.tag"),
        ),
    ]
