# Generated by Django 5.1.4 on 2025-01-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cue_intro",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="cue_outro",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="cart",
            name="cue_start",
            field=models.FloatField(default=0),
        ),
    ]
