# Generated by Django 3.1.3 on 2020-11-20 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0002_auto_20201118_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioUploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued for upload"),
                            ("ERROR", "Error"),
                            ("VALIDATING", "Confirming the file is an audio file"),
                            ("DECOMPRESSING", "Decompressing the audio"),
                            ("METADATA", "Extracting metadata"),
                            ("COMPRESSING", "Generating compressed version"),
                            ("DONE", "Successfully processed the audio"),
                        ],
                        default="QUEUED",
                        max_length=13,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alldaydj.cart"
                    ),
                ),
            ],
        ),
    ]
