# Generated by Django 3.1.7 on 2021-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0006_auto_20210122_1857"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="fade",
            field=models.BooleanField(default=False),
        ),
    ]
