# Generated by Django 3.1.7 on 2021-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0007_cart_fade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="display_artist",
            field=models.TextField(blank=True),
        ),
    ]
