# Generated by Django 3.2.8 on 2021-10-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0008_auto_20210502_1353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cue_intro_start",
        ),
    ]
