version: 2
updates:
  - package-ecosystem: "pip" #
    directory: "/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend/alldaydj/"
    schedule:
      interval: "daily"
