# Generated by Django 3.1.4 on 2021-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alldaydj", "0004_audiouploadjob_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="hash_audio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="hash_compressed",
            field=models.TextField(null=True),
        ),
    ]
