name: Build Containers
on:
    push:
        branches:
            - main

jobs:
    backend:
        runs-on: ubuntu-latest
        name: Build Backend Container
        steps:
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alldaydj-backend:latest
                context: "{{defaultContext}}:Backend"