name: Linting
on: [push]

jobs:
    backend:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.13"]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3  
            - name: Setup Python {{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Install Dependencies
              run: |
                    /home/runner/.local/bin/poetry install
              working-directory: ./Backend
            - name: Lint
              run: |
                    /home/runner/.local/bin/poetry run black --check --diff .
              working-directory: ./Backend
    frontend:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.13"]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3  
            - name: Setup Python {{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Install Dependencies
              run: |
                    /home/runner/.local/bin/poetry install
              working-directory: ./Frontend
            - name: Lint
              run: |
                    /home/runner/.local/bin/poetry run black --check --diff .
              working-directory: ./Frontend